### ISSUE TITLE
关于使用步骤的问题

### ISSUE THREAD

**Issue by double1991** [X-LANCE/Mobile-Env#2]
你好兄弟：我们现在尝试使用这个项目中的simple ，本地已经搭建好android 的SDK 和创建出来了虚拟机。但是我们在尝试调用你们simle 中的代码的时候一直失败的，提示拒绝访问，由于你们的说明文档实在是难以理解且步骤太不详细，所以在此提问想请兄帮忙解决下我们使用你们这个项目的问题，谢谢！

**Comment by double1991** [comment]
我们使用的脚本是run_random_agent.py，在这个脚本配置了sdk和avd相关的路径，使用的是虚拟机上面安装的是2048游戏app

**Comment by zdy023** [comment]
你好，你们具体遇到的是什么问题？
